services:
  # Uncomment the following lines to use payara servr container in local development
  payara_server:
    container_name: payara_server
    build: 
      context: .
      dockerfile: ./docker/payara/Dockerfile
    ports:
      - 4848:4848
      - 8080:8080
    environment:
      - dbHost=db
      - dbPort=3306
      - dbName=db
      - dbUser=root
      - dbPassword=password

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/init.d:/docker-entrypoint-initdb.d
      - ./docker/database/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
